---
servicediscovery:
  host: localhost
  port: 8010
  url: http://localhost:8010/eureka/


# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: ${servicediscovery.url}

lucky-word: Serendipity


dashboard:
  port: 8078
  
  
cloudconfig:
  port: 8001

  
---
  