---

service-discovery:
  host:localhost
  port: 8010
  url: http://${service-discovery.host}:${service-discovery.port}/eureka/

# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: ${service-discovery.url}

lucky-word: Serendipity
---
  