---

servicediscovery:
  host: localhost
  port: 8010
  url: http://${servicediscovery.host}:${servicediscovery.port}/eureka/

# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: ${servicediscovery.url}

lucky-word: Serendipity
---
  